version: '3.7'
services:
  app:
    build: ./docker/app
    working_dir: /var/www
    volumes:
      - ./:/var/www/
    networks:
      - mobile
  cron:
    build: ./docker/cron
    working_dir: /var/www
    volumes:
      - ./:/var/www/
    networks:
      - mobile
  web:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/log:/var/log/nginx
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - mobile
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=mobile
      - MYSQL_ROOT_PASSWORD=dev
    volumes:
      - dbmobile:/var/lib/mysql
    networks:
      - mobile
    ports:
      - "3307:3306"
  redis:
    image: "redis:alpine"
    networks:
        - mobile

#Docker Networks
networks:
  mobile:
    driver: bridge

volumes:
    dbmobile:
